name: RCSkills
main: com.silthus.rcskills.RCSkills
version: 1.5
database: true
authors:
  - Silthus
website: www.raid-craft.de
description: >
             Provides an Level and EXP System based on Groups
commands:
    lvlup:
        aliases: [lvl, levelup]
        description: Makes it possible for Players to LevelUP.
        usage: |
           /<command>
           Example: /<command> | Takes you to the next Level
           Example: /<command> top | Shows the Top 5 leveled Players
           Example: /<command> exp | Shows your current EXP