name: RCSkills
main: com.silthus.rcskills.RCSkills
version: 1.2
database: true
authors:
  - Silthus
website: www.raid-craft.de
description: >
             Provides an Level, Skills and EXP System based on Groups
commands:
    rcs:
        aliases: [lvlup]
        description: The RaidCraft Server plugin.