name: RCSkills
main: com.silthus.rcskills.RCSkills
version: 2.0
database: true
authors:
  - Silthus
website: www.raid-craft.de
description: >
             Provides an Level, Skills and EXP System based on Groups
commands:
    rcs:
        aliases: [lvlup]
        description: The RaidCraft Server plugin.
        usage: |
           /<command>
           Example: /<command> | Shows you your basic stats
           Example: /<command> lvl | Takes you to the next level
           Example: /<command> skills | Lists all skills you can buy